language: node_js
node_js:
  - 8
env:
  - TEST_DIR=client
  - TEST_DIR=server
script:
  - cd $TEST_DIR && npm install && npm run build
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: client/build
  on:
    branch: master
