language: node_js
node_js:
  - 8
env:
script:
  - cd client && npm install && npm run build
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
